### PR TITLE
Cache Font objects to limit number created

### PR DESCRIPTION
**Pull request by r1chardj0n3s**
This change caches the creation of Fonts, required for some of my testing where too many Font objects were being created and eventually failed.

### CODE REVIEW

**Comment by r1chardj0n3s** [comment]
Oh, my apologies for the spurious whitespace changes in the diff :-(

**Comment by aeby** [comment]
Thanks for your work. Can you please remove the white-space changes and the print statement - then I'm happy to merge ;-)

**Comment by aeby** [comment]
fixed in https://github.com/atizo/PyTagCloud/commit/af0cc97cfc52632e05510f5a1c0b0c444073b27b

**Comment by r1chardj0n3s** [comment]
Sorry I couldn't be more helpful :-)

**Pull request closed without merging**
